# to be placed in /etc/microshift/config.yaml
dns:
  baseDomain: microshift.is-in-the.cloud
network:
  clusterNetwork:
    - cidr: 10.42.0.0/16
  serviceNetwork:
    - 10.43.0.0/16
  serviceNodePortRange: 30000-32767
debugging:
  logLevel: "Normal"