apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certs
spec:
  destination:
    name: 'cert-man'
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.13.0
    chart: cert-manager
    helm:
      valueFiles:
        - values.yaml
      values: |-
        prometheus:
          enabled: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true