apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-console
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: workloads/console
    repoURL: https://github.com/springdo/microshift.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true