apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: plant-data
    server: https://kubernetes.default.svc
  project: default
  source:
    path: workloads/grafana
    repoURL: https://github.com/springdo/microshift.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true