---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  ports:
    - port: 9093
      protocol: TCP
      targetPort: 9093
      name: 9093-tcp
  selector:
    deployment: alertmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}