---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miflora-prometheus
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: miflora-prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: miflora-prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus
        imagePullPolicy: Always
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --web.config.file=/etc/prometheus/web-config.yml
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: miflora-prometheus-config
        - mountPath: /prometheus
          name: miflora-prometheus-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: miflora-prometheus
        name: miflora-prometheus-config
      - name: miflora-prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-pvc