---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  miflora-prometheus
data:
  web-config.yml: |-
    basic_auth_users:
      microshift: $2y$05$yJw7zBr4OMz0RiDS5Z4UT.tBmCdrLsbGvE9Wtvmw2dAEdyljFfNSy
      grafana: $2y$05$rnmbj3jPZBtM1xv5GnT2WegH7lJIyuL3h.YZ4J/uQWC0IYwjDfI1S
  prometheus.yml: |-
    global:
      scrape_interval:     3600s
      evaluation_interval: 3600s

    rule_files:
      - moisture.rules

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      # Living Room Scrapes
      - job_name: baldy_ficus 
        metrics_path: '/'
        static_configs:
          - targets: ['192.168.86.30:6000']
            labels: 
              instance: living_room
              sensor: B
      - job_name: rubber_tree
        metrics_path: '/'
        static_configs:
          - targets: ['192.168.86.30:6001']
            labels: 
              instance: living_room
              sensor: C
      - job_name: japanese_bamboo
        metrics_path: '/'
        static_configs:
          - targets: ['192.168.86.30:6002']
            labels: 
              instance: living_room
              sensor: D
      - job_name: sideshow_bob
        metrics_path: '/'
        static_configs:
          - targets: ['192.168.86.30:6003']
            labels: 
              instance: living_room
              sensor: G

      # Bedroom 
      - job_name: cheese_plant
        metrics_path: '/'
        static_configs:
          - targets: ['192.168.86.29:6011']
            labels: 
              instance: bedroom
              sensor: K
      # - job_name: money_tree
      #   metrics_path: '/'
      #   static_configs:
      #     - targets: ['192.168.86.29:6012']
      #       labels: 
      #         instance: bedroom
      #         sensor: 

      # Babyroom - pi name but kitcken is location
      - job_name: aralia_fabian
        metrics_path: '/'
        static_configs:
          - targets: ['192.168.86.34:6020']
            labels: 
              instance: kitchen
              sensor: E
      - job_name: small_rubber_tree
        metrics_path: '/'
        static_configs:
          - targets: ['192.168.86.34:6021']
            labels: 
              instance: kitchen
              sensor: F
      - job_name: pink_rubber
        metrics_path: '/'
        static_configs:
          - targets: ['192.168.86.34:6022']
            labels:
              instance: kitchen
              sensor: I
      # - job_name: aralia_fabian
      #   metrics_path: '/'
      #   static_configs:
      #     - targets: ['192.168.86.34:6022']
      #       labels: 
      #         instance: kitchen

      # Spareroom - but actually in the hallway
      - job_name: spider_plant
        metrics_path: '/'
        static_configs:
          - targets: ['192.168.86.39:6030']
            labels: 
              instance: hallway
              sensor: H
      - job_name: begonia
        metrics_path: '/'
        static_configs:
          - targets: ['192.168.86.39:6031']
            labels: 
              instance: hallway
              sensor: J

    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager:9093"
  moisture.rules: |-
    groups:
    - name: moisture.rules
      rules:
      - alert: DryPlants
        expr: miflora_primary{resource_type="moisture"} < 10
        annotations:
          DESCRIPTION: '{{$labels.job}} dry plant'
          SUMMARY: '{{$labels.job}} in {{$labels.instance}} needs to be watered'