apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: miflora-prometheus
spec:
  host: prometheus.apps.microshift.is-in-the.cloud
  port:
    targetPort: 9090
  tls:
    termination: edge
  to:
    kind: Service
    name: miflora-prometheus
    weight: 100
  wildcardPolicy: None
status: {}