apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf
data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://miflora-prometheus:9090
