{
 "title": "🌻 FlowerPower2.0 🌷",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "📺 Livingroom Moisture",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "miflora_primary{instance=\"living_room\",resource_type=\"moisture\"}",
     "legendFormat": "Sensor {{sensor}} | {{job}}"
    }
   ]
  },
  {
   "title": "🚪 Hallway Moisture",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "miflora_primary{instance=\"hallway\",resource_type=\"moisture\"}",
     "legendFormat": "Sensor {{sensor}} | {{job}}"
    }
   ]
  },
  {
   "title": "🛌 Bedroom Moisture",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "miflora_primary{instance=\"bedroom\",resource_type=\"moisture\"}",
     "legendFormat": "Sensor {{sensor}} | {{job}}"
    }
   ]
  },
  {
   "title": "👩‍🍳🍳 Kitchen Moisture",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "miflora_primary{instance=\"kitchen\",resource_type=\"moisture\"}",
     "legendFormat": "Sensor {{sensor}} | {{job}}"
    }
   ]
  },
  {
   "title": "☀️ All Sunlight",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "miflora_primary{resource_type=\"light\"}",
     "legendFormat": "Sensor {{sensor}} | {{instance}}"
    }
   ]
  },
  {
   "title": "🌡️ All Temperature",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "miflora_primary{resource_type=\"temperature\"}",
     "legendFormat": "Sensor {{sensor}} | {{instance}}"
    }
   ]
  },
  {
   "title": "🌿 All Moisture",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "miflora_primary{resource_type=\"moisture\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miflora_primary{resource_type=\"battery\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}